### PR TITLE
Fix null_ll for poisson noise.

### PR DESCRIPTION
**Pull request by petrroll**
LL for poissson noise should be $m\*log(p)-p$ where p: predicted and m: measured. Thus for static model, over all data it leads to $l\*ln(l)-l$ or $l*(ln(l)-1)$ where $l$ is mean of the measured data.

### CODE REVIEW

**Comment by petrroll** [comment]
I'm actually unsure about this one so please double check if it's correct.

**Comment by dbutts** [comment]
This is quite a over-complicated issue that I’ve thought though, but always could probably talk more. The main issue is that the null-adjustment (LL of the null model) has to be the same units as the LLs. As currently implemented, there is a variable: “self.poisson_unit_norm” that effectively normalizes each unit by its firing rate x the time interval (i.e. total number of spikes). It is implemented the way it is for complex reasons to do with stability, which I can further explain. However, this means that the LLs calculated are normalized by total spikes, so should the null-LL. In fact, usually LLs are reported in bits/spk (also normalized by the total spikes).

I think as it was, it is all consistent, and will not implement this (yet). We can discuss further of course…

**Comment by petrroll** [comment]
Ah, that makes perfect sense. Reverted the change + added docs explaining why it works this way. 

This should be fine until I figure out how to use `self.poisson_unit_norm` in `get_null_ll` to normalize the `ll` properly even if `self.poisson_unit_norm` isn't mean of measured data (current default). There're a few ways but I'm gonna do it I want it to be architecturally sound and work properly.

**Comment by dbutts** [comment]
Apparently this did nothing other than add comments/additional explanation (thanks!)

**Pull request merged**
