### PR TITLE
Fix init for training params.

### PR DESCRIPTION
**Pull request by petrroll**

### CODE REVIEW

**Comment by petrroll** [comment]
Fixes initialization of some parameters for one type of learning alg.

**Comment by petrroll** [comment]
BTW: It might be beneficial if I could eventually (1) get added to https://github.com/NeuroTheoryUMD so that I have write access to this repository. I'd *still* submit *all breaking changes* via my own fork and PR but for small fixes like this one I could commit them directly. 

It would increase my productivity (less time spend on syncing my fork/your version), lessen the burden/overhead for you, ...

> 1: I know I'm new here, I wouldn't trust myself immediately either :)
---
Another possibility is that I can make more changes to my own fork of NDN3 and submit PR for review in bigger chunks once in a while. That might, however, has its own set of issues. 

It would probably be more difficult to review individual changes and approve/deny them if only some of them were desirable by you (both breaking&not breaking would be together) and could generally lead to us going out of sync more often.

---

Or we can continue like this where I'll submit individual changes for PR on their own. Not sure how scalable it will be going further, however (it might be perfectly fine, who knows).

**Comment by dbutts** [comment]
Hi Petr,

I’ve been meaning to respond sooner (as well as commit your changes) but I’ve got a bunch of deadlines this week and haven’t been able to code. Hope to catch up a bt tomorrow, and hope to respond to everythiing. One thing I realize is I deleted a couple files stupidly (TLayer) that I’ll need to restore. 

Anyway thanks for all these contributons so far! More soon,
:Dan

**Comment by petrroll** [comment]
No worries, I'm not blocked in any way so it's non-issue. Also, in case you encounter conflicts etc. I'm happy to help with anything (git can be a mysterious beast sometimes).

**Pull request merged**
